### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by abhianan** [openscoring/openscoring#35]
Hi,
  I am using openscoring server for deploying my 400 models in one go but while i gave all these model as PMML file to server it was not able to run all of them and threw an error [mentioned below] . Please tell me how i can fix the problem.
Thank You

> Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.createInstance(ClassBeanInfoImpl.java:298)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.createInstance(UnmarshallingContext.java:701)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:186)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:576)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:555)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:168)
	at org.xml.sax.helpers.XMLFilterImpl.startElement

> (XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at org.openscoring.service.ModelRegistry.unmarshal(ModelRegistry.java:190)
	at org.openscoring.service.ModelRegistry.load(ModelRegistry.java:114)
	at org.openscoring.service.ModelResource.doDeploy(ModelResource.java:179)
	at org.openscoring.service.ModelResource.deploy(ModelResource.java:157)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
>  Jul 25, 2017 9:17:12 AM org.eclipse.jetty.server.HttpChannel handleException  WARNING: Could not send response error 500: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by vruusmann** [comment]
> Please tell me how i can fix the problem.

Increase JVM heap size by specifying `-Xms` and `-Xmx` command-line options.

Additionally, you may want to optimize the run-time representation of PMML class model objects by applying a series of interner-type Visitors to them. It's explained in the README file.
