### ISSUE TITLE
Client side throw an exception that java.lang.IllegalStateException: InjectionManagerFactory not found.

### ISSUE THREAD

**Issue by zhangzxgf** [openscoring/openscoring#41]
hello,
I have a problem when running:
`java -cp client-executable-1.4.1.jar org.openscoring.client.Deployer --model http://localhost:8080/openscoring/model/DecisionTreeIris --file DecisionTreeIris.pmml`
The exception is:
```
Exception in thread "main" java.lang.IllegalStateException: InjectionManagerFactory not found.
        at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
        at java.util.Optional.orElseThrow(Unknown Source)
        at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
        at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
        at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
        at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.buildPut(JerseyInvocation.java:238)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.buildPut(JerseyInvocation.java:171)
        at org.openscoring.client.Deployer$1.perform(Deployer.java:81)
        at org.openscoring.client.Deployer$1.perform(Deployer.java:71)
        at org.openscoring.client.ModelApplication.execute(ModelApplication.java:51)
        at org.openscoring.client.Deployer.deploy(Deployer.java:90)
        at org.openscoring.client.Deployer.run(Deployer.java:58)
        at org.openscoring.client.Application.run(Application.java:64)
        at org.openscoring.client.Deployer.main(Deployer.java:53)
```
How can I resove the problem? Any help will be appreciated!

**Comment by vruusmann** [comment]
What's your Java version?
```
$ java -version
```

In the meantime, please switch to "raw" command-line client such as `curl`.

**Comment by zhangzxgf** [comment]
my java -version:
```
java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
