### ISSUE TITLE
IllegalArgumentException: Attribute 'GradientBoostingClassifier.loss_' has an unsupported value (Python class BinomialDeviance)

### ISSUE THREAD

**Issue by sam-s** [openscoring/openscoring#49]
I am getting this error:
```
Standard error:
May 16, 2019 10:09:35 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 16, 2019 10:09:35 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 60 ms.
May 16, 2019 10:09:35 AM org.jpmml.sklearn.Main run
INFO: Converting..
May 16, 2019 10:09:35 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Attribute 'sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.loss_' has an unsupported value (Python class sklearn.ensemble._gb_losses.BinomialDeviance)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.PyClassDict.get(PyClassDict.java:57)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.getLoss(GradientBoostingClassifier.java:121)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:67)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:42)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.ensemble.gradient_boosting.LossFunction
	at java.base/java.lang.Class.cast(Class.java:3611)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 7 more

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.loss_' has an unsupported value (Python class sklearn.ensemble._gb_losses.BinomialDeviance)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.PyClassDict.get(PyClassDict.java:57)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.getLoss(GradientBoostingClassifier.java:121)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:67)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:42)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.ensemble.gradient_boosting.LossFunction
	at java.base/java.lang.Class.cast(Class.java:3611)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 7 more
```
from fbd663c74ca0d0c727504ddd1a87b14f8abfee00

**Comment by vruusmann** [comment]
Handling this issue at the jpmml/jpmml-sklearn project level.
